defaults:
  - model: lacc
  - data: data
  - logger: mlflow
  - export: export
  - _self_

seed: 2004

paths:
  checkpoints_dir: checkpoints
  plots_dir: plots

logging:
  level: INFO
  log_file: logs/run.log

trainer:
  max_epochs: 6
  accelerator: auto
  devices: 1
  precision: "32"
  log_every_n_steps: 50

export:
  auto_export_onnx: true
  auto_export_trt: false

triton:
  repo_dir: triton_models
  model_name: captcha_rec_lacc
  max_batch_size: 8
